Repository projectsyn/component-rook-ceph, pull requests merged in 2022-07, with the labels that each got.

#72 Allow CSI provisioner pods to be scheduled on the storage nodes
  class/defaults.yml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
Labels: enhancement

#70 Update Helm release rook-ceph to v1.9.6
  class/defaults.yml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/psp.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/psp.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
Labels: dependency

#68 Update dependency docker.io/bitnami/kubectl to v1.24.2
  class/defaults.yml
  tests/golden/defaults/rook-ceph/rook-ceph/99_cleanup.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/99_cleanup.yaml
Labels: dependency

#76 Allow the default SA in the operator namespace to use the Ceph-CSI SCC
  component/openshift.libsonnet
  tests/golden/openshift4/rook-ceph/rook-ceph/02_openshift_sccs.yaml
Labels: bug

#19 Properly expose configuration for storageClassDeviceSets
  class/defaults.yml
  component/cephcluster.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement
