Repository projectsyn/component-rook-ceph, pull requests merged in 2022-04, with the labels that each got.

#39 Rename the helm chart release_name variable for Kapitan to name
  class/rook-ceph.yml
Labels: dependency

#41 Configure modulesync
  .sync.yml
  tests/defaults.yml
Labels: ignore

#44 Add support for patching alert rules through the hierarchy
  class/defaults.yml
  component/alertrules.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#31 Update dependency quay.io/ceph/ceph to v16.2.7
  class/defaults.yml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
Labels: dependency

#49 Configure `openshift4` golden tests
  .sync.yml
  tests/golden/openshift4/rook-ceph/apps/rook-ceph.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/00_namespaces.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/psp.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/resources.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/02_openshift_sccs.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_configoverride.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_rbac.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/20_storagepools.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/30_snapshotclasses.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/30_storageclasses.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/40_alertrules.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/40_csi_driver_metrics.yaml
  tests/openshift4.yml
Labels: ignore

#48 Update `rook-ceph` to v1.8.8
  class/defaults.yml
  class/rook-ceph.yml
  component/cephcluster.libsonnet
  component/openshift.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/psp.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/resources.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/40_alertrules.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/02_openshift_sccs.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
Labels: dependency, breaking

#51 Upgrade `ceph-csi` to v3.5.1
  class/defaults.yml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
Labels: dependency

#52 Update `rook-ceph` to v1.8.9
  class/defaults.yml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/psp.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/psp.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
Labels: dependency
