Repository projectsyn/component-rook-ceph, pull requests merged in 2023-11, with the labels that each got.

#124 Upgrade Rook to 1.11.11
  class/defaults.yml
  component/cephcluster.libsonnet
  docs/modules/ROOT/pages/runbooks/CephDaemonSlowOps.adoc
  docs/modules/ROOT/pages/runbooks/CephDeviceFailurePredicted.adoc
  docs/modules/ROOT/pages/runbooks/CephFilesystemInsufficientStandby.adoc
  docs/modules/ROOT/pages/runbooks/CephFilesystemMDSRanksLow.adoc
  docs/modules/ROOT/pages/runbooks/CephMgrModuleCrash.adoc
  docs/modules/ROOT/pages/runbooks/CephMonClockSkew.adoc
  docs/modules/ROOT/pages/runbooks/CephNodeInconsistentMTU.adoc
  docs/modules/ROOT/pages/runbooks/CephNodeNetworkPacketDrops.adoc
  docs/modules/ROOT/pages/runbooks/CephOSDBackfillFull.adoc
  docs/modules/ROOT/pages/runbooks/CephOSDFlapping.adoc
  docs/modules/ROOT/pages/runbooks/CephOSDFull.adoc
  docs/modules/ROOT/pages/runbooks/CephOSDInternalDiskSizeMismatch.adoc
  docs/modules/ROOT/pages/runbooks/CephOSDNearFull.adoc
  docs/modules/ROOT/pages/runbooks/CephOSDReadErrors.adoc
  docs/modules/ROOT/pages/runbooks/CephOSDTimeoutsClusterNetwork.adoc
  docs/modules/ROOT/pages/runbooks/CephOSDTimeoutsPublicNetwork.adoc
  docs/modules/ROOT/pages/runbooks/CephObjectMissing.adoc
  docs/modules/ROOT/pages/runbooks/CephPGBackfillAtRisk.adoc
  docs/modules/ROOT/pages/runbooks/CephPGImbalance.adoc
  docs/modules/ROOT/pages/runbooks/CephPGNotDeepScrubbed.adoc
  docs/modules/ROOT/pages/runbooks/CephPGNotScrubbed.adoc
  docs/modules/ROOT/pages/runbooks/CephPGRecoveryAtRisk.adoc
  docs/modules/ROOT/pages/runbooks/CephPGsUnclean.adoc
  docs/modules/ROOT/pages/runbooks/CephPoolBackfillFull.adoc
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/resources.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/40_alertrules.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/99_cleanup.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/resources.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/40_alertrules.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/99_cleanup.yaml
Labels: breaking

#135 Update module github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring to v0.68.0
  tools/runbooks-from-upstream/go.mod
  tools/runbooks-from-upstream/go.sum
Labels: dependency

#109 Update docker.io/bitnami/kubectl Docker tag to v1.28.3
  class/defaults.yml
  tests/golden/defaults/rook-ceph/rook-ceph/99_cleanup.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/99_cleanup.yaml
Labels: dependency

#114 Update quay.io/cephcsi/cephcsi Docker tag to v3.9.0
  class/defaults.yml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
Labels: dependency

#137 Update docker.io/bitnami/kubectl:1.28.3 Docker digest to 0defec7
  class/defaults.yml
  tests/golden/defaults/rook-ceph/rook-ceph/99_cleanup.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/99_cleanup.yaml
Labels: dependency

#139 Add how-to for upgrading to Ceph-CSI v3.9.0
  docs/modules/ROOT/pages/how-tos/upgrade-ceph-csi-v3.9.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/cephfs/rook-ceph/rook-ceph/99_cleanup.yaml
Labels: documentation

#141 Update docker.io/bitnami/kubectl Docker tag to v1.28.4
  class/defaults.yml
  tests/golden/cephfs/rook-ceph/rook-ceph/99_cleanup.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/99_cleanup.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/99_cleanup.yaml
Labels: dependency
