Repository projectsyn/component-rook-ceph, pull requests merged in 2024-04, with the labels that each got.

#142 Update dependency Rook to v1.14.2 (minor)
  class/defaults.yml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/resources.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/40_csi_driver_metrics.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/resources.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/40_csi_driver_metrics.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/resources.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/40_csi_driver_metrics.yaml
Labels: dependency

#156 Set default value for monitor healthcheck
  class/defaults.yml
  tests/golden/cephfs/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
Labels: bug

#157 Rook v1.14: Add new `rook-ceph-default` SA to copy helper
  component/cephcluster.libsonnet
  tests/golden/cephfs/rook-ceph/rook-ceph/10_cephcluster_rbac.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_rbac.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_rbac.yaml
Labels: bug

#158 Rook v1.14: Switch `enableCSIHostNetwork` to upstream default
  class/defaults.yml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
Labels: change

#159 Rook v1.14: Add cluster default SA to OpenShift SCC
  component/openshift.libsonnet
  tests/golden/openshift4/rook-ceph/rook-ceph/02_openshift_sccs.yaml
Labels: bug

#161 Rook v1.14: Remove holder pod restart logic
  component/main.jsonnet
  component/restart-holder-ds.libsonnet
  tests/golden/cephfs/rook-ceph/rook-ceph/50_restart_holder_ds.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/50_restart_holder_ds.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/50_restart_holder_ds.yaml
Labels: breaking

#144 Update quay.io/cephcsi/cephcsi Docker tag to v3.11.0
  class/defaults.yml
Labels: dependency

#162 Fix `cephcsi` image override
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: bug
