Repository projectsyn/component-rook-ceph, pull requests merged in 2025-01, with the labels that each got.

#208 Update docker.io/rook/ceph Docker tag to v1.15.8
  class/defaults.yml
  tests/golden/cephfs/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/cephfs/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
  tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
  tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
Labels: dependency, automerge, bump:patch

#209 Add support for OKE as an OpenShift flavor
  component/alertrules.libsonnet
  component/cephcluster.libsonnet
  component/csi_metrics.libsonnet
  component/helpers.libsonnet
  component/main.jsonnet
Labels: enhancement

#210 Switch Helm chart definition to Project Syn best practices
  class/defaults.yml
  class/rook-ceph.yml
Labels: dependency
